### ISSUE TITLE
Changing API + GL + HL

### ISSUE THREAD

**Issue by swstarone** [hahadaba/vue3-scaffold#1]
dear sir need to change all these 3 when changing GL (country)

GL    = Region
HL    = Language
API   = Different API Key selection

**Comment by hahadaba** [comment]
This project is to select GL.
It's easy to make API selector just like GL selector.
The YOU2PHP has only Chinese language version.You can modify the scripts and translate the language by youself.

**Comment by swstarone** [comment]
How can we add more than one Youtube API ?

**Comment by ancct** [comment]
@hahadaba 这个非常不错，不用频繁的修改了，但是我在网页上集成翻译代码这里遇到了问题。谷歌翻译代码很好用，但是com接口墙内用不了。cn接口一用就会被墙。有什么好的解决办法吗？

**Comment by hahadaba** [comment]
@swstarone I have no plan to add api selector,sorry.

**Comment by hahadaba** [comment]
@ancct 没研究过翻译啊，抱歉。
我可能稍后研究一下能否加入youtube账号登录功能。

**Comment by koolwiki** [comment]
@swstarone 如果能登录就好了
